# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: Pod Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

jobs:
  main:
    name: Pod Lint
    runs-on: macos-14
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version

      - name: pod lint
        run: pod lib lint --verbose
